spring.application.name=MedicalHealthcareApi

# Use integratedSecurity=true for Windows Authentication and trustServerCertificate=true to match SSMS settings
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=medical_healthcare_db;integratedSecurity=true;encrypt=true;trustServerCertificate=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true